config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'login', to: 'sessions#update'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :update]
  resources :events do
    member do
      get :followers
    end
  end  
  resources :messages
  
  resources :comments, only: [:create, :destroy]
  resources :participates, only: [:create, :destroy]
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 800 }
  has_many :comment, dependent: :destroy
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @messages = Message.all.order('created_at DESC').page(params[:page]).per(30)
  end

  def show
    @comment = current_user.comment.build
    @comments = Message.find_by(id: params[:id]).comment.page(params[:page])
  end

  def new
    @message = Message.new
  end

  def create
    @message = current_user.message.new(message_params)

    if @message.save
      flash[:success] = 'Message が正常に投稿されました'
      redirect_to @message
    else
      flash.now[:danger] = 'Message が投稿されませんでした'
      render :new
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      flash[:success] = 'Message は正常に更新されました'
      redirect_to @message
    else
      flash.now[:danger] = 'Message は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @message.destroy

    flash[:success] = 'Message は正常に削除されました'
    redirect_to messages_url
  end
  
  private

  # Strong Parameter
  def message_params
    params.require(:message).permit(:title, :content)
  end
  def correct_user
    @message = Message.find_by(id: params[:id])
    unless @message
      redirect_to message_url
    end
  end
  

end

app/views/messages/_form.html.erb
<div class="row">
  <div class="col-lg-9">

    <%= form_for(@message) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :content, '内容' %>
        <%= f.text_area :content, class: 'form-control', rows: 5 %>
      </div>
    
      <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
    <% end %>

  </div>
</div>

app/views/messages/_message_table.html.erb
    <table class="table">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">タイトル</th>
          <th scope="col">作成者</th>
          <th scope="col">内容</th>
          <th scope="col">投稿日</th>
        </tr>
      </thead>
      <tbody>
        <% @messages.each do |e| %>
        <tr>
          <th scope="row"><%= e.id %></th>
          <td><%= link_to e.title, e %></td>
          <td><%= e.user.name %></td>
          <td><%= e.content %></td>
          <td><%= e.created_at.to_s(:published_on) %></td>
        </tr>
      　<% end %>
      </tbody>
    </table>

app/views/messages/edit.html.erb
<h1>id: <%= @message.id %> のメッセージ編集ページ</h1>

<%= render 'form' %>

<%= link_to '一覧に戻る', messages_path %>

app/views/messages/index.html.erb
<h1>Free Space 一覧</h1>

<div class="message">
  <%= render 'message_table' %>
  <%= link_to '新規messageの投稿', new_message_path , class:"btn btn-outline-pr btn-sm" %>
  <%= paginate @messages %>
</div>

app/views/messages/new.html.erb
<h1>メッセージ新規作成ページ</h1>

<%= render 'form' %>

<%= link_to '一覧に戻る', messages_path %>

app/views/messages/show.html.erb
<h1>id: <%= @message.id %> のメッセージ詳細ページ</h1>


  <div class="message-show">
    <p>タイトル：<%= @message.title %></p>
    <p><%= simple_format(@message.content) %></p>
    
    <%= link_to '一覧に戻る', messages_path, class:"btn btn-outline-secondary" %>
    <%= link_to 'このメッセージを編集する', edit_message_path(@message), class:"btn btn-outline-dark" %>
    <%= link_to 'このメッセージを削除する', @message, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class:"btn btn-outline-danger" %>
  </div>
  
  <div class="comment-form">
    <h4>コメント</h4>
    <%= render 'comments/comment_create' %>
  </div>
  <div class="comment-index">
    <%= render 'comments/comment_index' %>
  </div>
 
  