config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'login', to: 'sessions#update'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :update]
  resources :events do
    member do
      get :followers
    end
  end  
  resources :messages
  
  resources :comments, only: [:create, :destroy]
  resources :participates, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :campus,:department, presence: true
  has_secure_password
  
  mount_uploader :image, ImageUploader
  has_many :message
  has_many :comment
  has_many :event
  
  has_many :participate
  has_many :participate_event, through: :participate, source: :event
  
  def like(event)
    unless self == event.user
      self.participate.find_or_create_by(event_id: event.id)
    end
  end

  def unlike(event)
    participate = self.participate.find_by(event_id: event.id)
    participate.destroy if participate
  end

  def bookmarking?(event)
    self.participate_event.include?(event)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  def show
    @user = User.find(params[:id])
    @events = @user.participate_event.order('created_at DESC').page(params[:page]).per(30)
    @messages = @user.message.order('created_at DESC').page(params[:page]).per(30)
    @count_events = @user.participate_event.count
    @count_messages = @user.message.count
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def update
    @user = User.find(params[:id])
    @events = @user.participate_event.order('created_at DESC').page(params[:page]).per(10)
    @messages = @user.message.order('created_at DESC').page(params[:page]).per(10)
 
    if current_user == @user
   
      if @user.update(user_params)
        flash[:success] = 'ユーザー情報を編集しました。'
        redirect_to @user
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
        render :show
      end   
     
    else
        redirect_to root_url
    end
  end
  
  
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :campus, :department, :grade, :password, :password_confirmation, :image, :image_cache)
  end
end

app/views/users/_user.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <div>
            <% if user.image? %>
              <%= image_tag user.image.url %>
            <% else %>
              <%= image_tag("/images/no-image.png") %>
            <% end %>
          </div>
        </div>
        <div class="media-body">
          <div>
            <%= link_to user.name , user_path(user) %>
          </div>
          <div>
            <%= user.campus %>
            <%= user.department %>
            <%= user.grade %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-lg-6 offset-lg-3">
    <div class="text-center">
      <h1>会員登録</h1>
    </div>
        <%= form_for(@user) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
          <div class="form-row">
            <div class="form-group col-4">
              <%= f.label :campus, 'キャンパス' %>
              <%= f.select :campus, [['',''],['日吉','日吉'], ['三田','三田'], ['矢上','矢上'], ['湘南藤沢','湘南藤沢'], ['信濃町','信濃町'], ['芝共立','芝共立']], {}, {class: 'form-control'} %>
            </div>
            
            <div class="form-group col-4">
              <%= f.label :department, '学部' %>
              <%= f.select :department, [['',''],['文','文'], ['経済','経済'], ['法','法'], ['商','商'], ['医','医'], ['理工','理工'], ['薬','薬'], ['看護医療','看護医療'], ['総合政策','総合政策'], ['環境情報','環境情報']], {}, {class: 'form-control'} %>
            </div>
            
            <div class="form-group col-4">
              <%= f.label :grade, '学年' %>
              <%= f.select :grade, [['',],['1年',1],['2年',2], ['3年',3], ['4年',4]], {}, {class: 'form-control'} %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-outline-pr btn-block' %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="icon text-center">
    <%= form_for(@user) do |f| %>
        <% if @user.image? %>
          <%= image_tag @user.image.url, onClick:"$('#upfile').click()" %>
        <% else %>
          <%= image_tag '/images/no-image.png', onClick:"$('#upfile').click()" %>
        <% end %>
      <%= f.file_field :image, style:"display:none;", id:"upfile"%>
      <%= f.hidden_field :image_cache %>
      
      <script type="text/javascript">
          $('input[type=file]').on('change', function (e) {
              console.log(e.target.files);
              if (e.target.files[0].size > 0) {
                  $(this).parents('form').submit();
              }
          });
      </script>

    <% end %>
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
  </div>
  <div class="status text-center">
    <ul>
      <li>
        <div class="status-label">Events</div>
        <div id="events_count" class="status-value">
          <%= @count_events %>
        </div>
      </li>
      <li>
        <div class="status-label">Free Space</div>
        <div id="events_count" class="status-value">
          <%= @count_messages %>
        </div>
      </li>
    </ul>
  </div>
</div>

<div class="event">
  <h2>Event</h2>
  <%= render 'events/event_table' %>
</div>
<div class="message">
  <h2>Free Space</h2>
  <%= render 'messages/message_table' %>
</div>