config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'login', to: 'sessions#update'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :update]
  resources :events do
    member do
      get :followers
    end
  end  
  resources :messages
  
  resources :comments, only: [:create, :destroy]
  resources :participates, only: [:create, :destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 800 }
  validates :deadline, presence: true
  mount_uploader :image, ImageUploader
  
  has_many :participate
  has_many :participate_user, through: :participate, source: :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @events = Event.all.order('created_at DESC').page(params[:page]).per(30)
  end

  def show
    
  end

  def new
    @event = Event.new
  end

  def create
    star = current_user.authority
    if star == true
      @event = current_user.event.new(event_params)
  
      if @event.save
        flash[:success] = 'Event が正常に投稿されました'
        redirect_to @event
      else
        flash.now[:danger] = 'Event が投稿されませんでした'
        render :new
      end
      
    else
      redirect_to :back
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:success] = 'Event は正常に更新されました'
      redirect_to @event
    else
      flash.now[:danger] = 'Event は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @event.destroy

    flash[:success] = 'Event は正常に削除されました'
    redirect_to events_url
  end
  
  def followers
    @event = Event.find(params[:id])
    @users = @event.participate_user.page(params[:page]).per(30)
    counts(@event)
  end
  
  private

  # Strong Parameter
  def event_params
    params.require(:event).permit(:title, :image, :content, :deadline)
  end
  def correct_user
    @event = Event.find_by(id: params[:id])
    unless @event
      redirect_to event_url
    end
  end
end

app/views/events/_event_table.html.erb
    <table class="table">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">タイトル</th>
          <th scope="col">作成者</th>
          <th scope="col">締切日</th>
          <th scope="col">投稿日</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |e| %>
        <tr>
          <th scope="row"><%= e.id %></th>
          <td><%= link_to e.title, e %></td>
          <td><%= e.user.name %></td>
          <td><% if e.deadline < Time.now %>
              <p>申し込みは終了しました。</p>
              <% else %>
              <%= e.deadline.to_s(:published_on)%>
              <% end %></td>
          <td><%= e.created_at.to_s(:published_on) %></td>
        </tr>
      　<% end %>
      </tbody>
    </table>

app/views/events/_form.html.erb
<div class="row">
  <div class="col-lg-9 offset-lg-1">

      <%= form_for(@event) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
          <div class="form-group">
          <%= f.label :title, 'タイトル' %>
          <%= f.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-row">
            <div class="form-group">
              <%= f.label :image, '画像ファイル：'%>
              <%= f.file_field :image %>
            </div>
            <div class="form-group">
              <%= f.label :deadline, '締切日指定：' %>
              <%= raw sprintf(
                f.datetime_select(
                  :deadline,# プロパティ名
                  {
                    start_year:     Time.zone.now.prev_year.year,# 選択可能な開始年
                    end_year:       Time.zone.now.next_year.year,# 選択可能な終了年
                    default:        Time.zone.now,# デフォルトの年
                    use_two_digit_numbers: true,# 月日を2桁の値で表示
                    date_separator: '%s',# 年, 月
                    datetime_separator: '%s',# 日
                    time_separator: '%s'# 時
                  },# オプション
                  { class: 'date-select' }# htmlオプションを指定する場合は別で指定
                ),
                '年 ', '月 ', '日 ', '時 ') + '分'# 分 は最後につけ加えられる
              %>
            </div>
          </div>
          <div class="form-group">
          <%= f.label :content, '内容' %>
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
          </div>
      
        <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
      <% end %>

   
  </div>
</div>

app/views/events/edit.html.erb
<h1>id: <%= @event.id %> のメッセージ編集ページ</h1>

<%= render 'form' %>

<%= link_to '一覧に戻る', events_path %>

app/views/events/followers.html.erb
<h1>参加人数<span class="badge badge-info"><%= @count_participates %></span></h1>

<div class="col-xs-8">
  <div class="participate-member">
    <%= render 'users/user', users: @users %>
  </div>
</div>

app/views/events/index.html.erb
<h1>Event 一覧</h1>

<div class="event">
  <%= render 'event_table' %>
  <% if current_user.authority == true%>
    <%= link_to '新規Eventの投稿', new_event_path , class:"btn btn-outline-pr btn-sm"%>
  <% end %>
  <%= paginate @events %>
</div>

app/views/events/new.html.erb
<h1>メッセージ新規作成ページ</h1>

<%= render 'form' %>

<%= link_to '一覧に戻る', events_path %>

app/views/events/show.html.erb
<h1>id: <%= @event.id %> のイベント詳細ページ</h1>
<div class="event-show">
<table class="table">
  <thead>
    <tr>
      <th>
        タイトル : <%= @event.title %>
      </th>
      <th>
        締切日 : 
        <% if @event.deadline? %>
        <%= @event.deadline.to_s(:published_on) %>
        <% else %>
        <% end %>
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>
        <% if @event.image? %>
            <%= image_tag @event.image.url %>
        <% else %>
            <%= image_tag("/images/icon/no-image.png") %>
        <% end %>
      </th>
      <td><%= simple_format(@event.content)%></td>
    </tr>
  </tbody>
</table>

<%= link_to '一覧に戻る', events_path, class:"btn btn-outline-secondary" %>

<% if current_user == @event.user%>
    <%= link_to 'このイベントを編集する', edit_event_path(@event), class:"btn btn-outline-dark" %>
    <%= link_to 'このイベントを削除する', @event, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class:"btn btn-outline-danger" %>
<% elsif logged_in? %>
    <% if @event.deadline < Time.now %>
        申し込みは終了しました。
        <% else %>
        <%= render 'participates/participate_button', event: @event %>
    <% end %>
<% end %>
<% if current_user.authority == true %>
    <%= link_to 'イベント参加者名簿', followers_event_path(@event), class:"btn btn-outline-light" %>
<% end %>
</div>